// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-wardrobe-items.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-wardrobe-items.ts
var list_wardrobe_items_default = defineTool({
  name: "list_wardrobe_items",
  title: "List wardrobe items",
  description: "List the signed-in user's wardrobe items, optionally filtered by category (dress, top, bottom, shoes, outerwear, accessory).",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter, e.g. dress, top, bottom, shoes, outerwear, accessory."),
    limit: z.number().int().optional().describe("Maximum number of items to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const capped = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabase.from("wardrobe_items").select("id, name, category, color, brand, size, tags, notes, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(capped);
    if (category) query = query.eq("category", category.toLowerCase().trim());
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-wardrobe-item.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.23.8";
var add_wardrobe_item_default = defineTool2({
  name: "add_wardrobe_item",
  title: "Add wardrobe item",
  description: "Add a garment to the signed-in user's wardrobe.",
  inputSchema: {
    name: z2.string().trim().describe("Short descriptive name, e.g. 'Black slip dress'."),
    category: z2.enum(["dress", "top", "bottom", "shoes", "outerwear", "accessory"]).describe("Garment category."),
    color: z2.string().optional().describe("Plain colour word, e.g. navy."),
    brand: z2.string().optional(),
    size: z2.string().optional(),
    notes: z2.string().optional().describe("Fabric or styling notes."),
    tags: z2.array(z2.string()).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, category, color, brand, size, notes, tags }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!name.trim()) {
      return { content: [{ type: "text", text: "Item name is required" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("wardrobe_items").insert({
      user_id: ctx.getUserId(),
      name: name.trim(),
      category,
      color: color ?? null,
      brand: brand ?? null,
      size: size ?? null,
      notes: notes ?? null,
      tags: tags ?? null
    }).select("id, name, category, color, brand, size, tags, notes");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { item: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/delete-wardrobe-item.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.23.8";
var delete_wardrobe_item_default = defineTool3({
  name: "delete_wardrobe_item",
  title: "Delete wardrobe item",
  description: "Permanently remove one garment from the signed-in user's wardrobe by its id.",
  inputSchema: {
    id: z3.string().describe("The wardrobe item id (uuid) returned by list_wardrobe_items.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("wardrobe_items").delete().eq("id", id).eq("user_id", ctx.getUserId()).select("id, name");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "No wardrobe item found with that id." }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Deleted "${data[0].name}".` }],
      structuredContent: { deleted: data[0] }
    };
  }
});

// src/lib/mcp/tools/get-style-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_style_profile_default = defineTool4({
  name: "get_style_profile",
  title: "Get style profile",
  description: "Read the signed-in user's style profile: sizes, budget, preferred and disliked colours and styles, body type and colour analysis.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_style_profiles").select(
      "display_name, body_type, face_shape, fit_preference, home_city, height_cm, budget_min, budget_max, budget_currency, preferred_colors, disliked_colors, preferred_brands, preferred_fabrics, disliked_styles, items_to_avoid, color_analysis"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "No style profile has been set up yet." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vjnsophqfxiamgjxnlls";
var mcp_default = defineMcp({
  name: "serena-outfitoracle",
  title: "serena-outfitoracle",
  version: "0.1.0",
  instructions: "Tools for Serena, a personal styling app. Read and manage the signed-in user's wardrobe with list_wardrobe_items, add_wardrobe_item and delete_wardrobe_item, and read their sizes, budget and colour preferences with get_style_profile. All data is scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_wardrobe_items_default, add_wardrobe_item_default, delete_wardrobe_item_default, get_style_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
